POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZGVqIiwiaWQiOiI2NzNjOWI2ZGJkZDkyNjU2YzU5OWVhZDAiLCJpYXQiOjE3MzIxOTY0ODZ9.w4Quk6OK7LN7AxJbxdI0Qqcod5vxktIGM712LGO1jVk

{
    "title": "Lisää blogeja",
    "author": "Ingrid Tuunela",
    "url": "www.osoite.com",
    "likes": 2,
}